name: Call API on PR Merge to Main

on:
  push:
    branches:
      - main  # Triggers only when something is pushed to main (e.g., after a PR merge)

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API after PR merge to main
        run: |
          curl -X POST https://webhook.site/c61d41b5-593d-4ed9-9861-c21808785a3f \
          -H "Content-Type: application/json" \
          -d '{
            "API-Message": "PR merged to main",
            "Github-Repository": "${{ github.repository }}",
            "Commit-Message": "${{ github.event.head_commit.message }}",
            "Commit-ID": "${{ github.sha }}",
            "Author": "${{ github.actor }}"
          }'
          