name: Call API on PR Merge to Main

on:
  push:
    branches:
      - main  # Triggers only when something is pushed to main (e.g., after a PR merge)

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API after PR merge to main
        run: |
          curl -X POST https://your-api-url.com/endpoint \
          -H "Content-Type: application/json" \
          -d '{
            "message": "PR merged to main",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}"
          }'
