name: Test API Call on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  test-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST to webhook.site
        run: |
          curl -X POST https://webhook.site/c61d41b5-593d-4ed9-9861-c21808785a3f \
          -H "Content-Type: application/json" \
          -d '{
            "message": "PR merged to main",
            "repo": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}"
          }'
